# Docker compose to build and run the eureka service
version: '3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8761:8761"
networks:
  default:
    external:
      name: springboot
