# Docker compose to build and run the eureka service
version: '3'
services:
  eureka-server.common.svc:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8761:8080"
networks:
  default:
    external:
      name: springboot
