spring:
  application:
    name: atto-eureka-server.common.svc
  cloud:
    config:
     uri: http://atto-config-server.common.svc:8080

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
